### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by jonbarrow**
Update the license to AGPLv3

Need permission from the following contributors to continue:

- [x] @Riven-Spell
- [x] @shutterbug2000 
- [x] @SuperMarioDaBom 
- [x] @Stary2001 
- [x] @superwhiskers

### CODE REVIEW

**Comment by superwhiskers** [comment]
i allow my contributions to be relicensed under the agplv3

**Comment by SuperMarioDaBom** [comment]
I give consent to my contributions being relicensed

**Comment by Riven-Spell** [comment]
I give consent for my contributions to be re-licensed to AGPL3.

**Comment by shutterbug2000** [comment]
Yeah that's fine.

**Comment by Stary2001** [comment]
I agree to relicense my contributions to AGPL3.

**Pull request merged**
