### PR TITLE
Remove streams in favor of crunch

### PR DESCRIPTION
**Pull request by Virepri**
As requested, I've removed all usages of the internal Input/Output streams with crunch buffers.

I did however, notice a couple of places that `bytes.Buffer` was used-- Were these intended to be replaced with crunch buffers as well?

### CODE REVIEW

**Comment by Virepri** [comment]
Will do

**Comment by Virepri** [comment]
Good for review

**Comment by adreed-msft** [comment]
❤️

**Comment by Virepri** [comment]
❤️

**Comment by superwhiskers** [comment]
♥️

**Pull request merged**
